language: python
python:
  - "3.2"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - pip install -r requirements.txt
script: 
  - python manage.py test cntapp/tests
  - python manage.py test functional_tests
